In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[65, 28],
       [76, 13],
       [99,  0],
       [63,  5],
       [54, 36],
       [59, 37],
       [31, 95],
       [24, 15],
       [67,  4],
       [61, 70]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.54666667, 0.29473684],
       [0.69333333, 0.13684211],
       [1.        , 0.        ],
       [0.52      , 0.05263158],
       [0.4       , 0.37894737],
       [0.46666667, 0.38947368],
       [0.09333333, 1.        ],
       [0.        , 0.15789474],
       [0.57333333, 0.04210526],
       [0.49333333, 0.73684211]])

In [9]:
scaler_model.fit_transform(data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

array([[0.54666667, 0.29473684],
       [0.69333333, 0.13684211],
       [1.        , 0.        ],
       [0.52      , 0.05263158],
       [0.4       , 0.37894737],
       [0.46666667, 0.38947368],
       [0.09333333, 1.        ],
       [0.        , 0.15789474],
       [0.57333333, 0.04210526],
       [0.49333333, 0.73684211]])

In [11]:
import pandas as pd

In [12]:
mydata =  np.random.randint(0,101,(50,4))

In [17]:
df = pd.DataFrame(data = mydata)

In [18]:
df

     0    1   2   3
0   18   43  54  69
1   99   97  59  54
2    9   97  98  51
3   90    5  91  51
4   70   18  98   7
5   68   30  60  65
6   94   61  22  68
7   80   97   8  76
8    5   19  51  86
9   26   32  61  46
10  53   97  40   9
11  16   76  89  91
12  93  100  43  98
13   9   57  68  89
14   2   89  70  64
15   2    5  97  63
16  54    2  94   1
17  89   74  51  67
18  20   20  21  25
19  10   32  71  13
20  21   65  63  40
21  18   38  89   9
22  64   23  14  26
23  43   91  41  70
24  89   98  61  25
25  30  100  30  28
26  90   79  35  32
27  76   82  40  16
28   9   52  76  51
29  69   65  11   3
30   4   74  46  93
31  98   10  94  31
32  19   53  57  96
33   5   46  69  89
34  28   69  43  69
35   3   88  43  33
36  57   75  88  57
37  67   57  77  30
38  50   19  82  62
39   8   67  59  55
40   3   31  72  53
41   8   94  36  86
42  69    8  79  72
43  37   33  86  93
44   6   10   2  64
45  90   36  54  94
46  91   22   9  35
47  57   44   2  95
48  48    4  90  42
49  35    3  19  22

In [21]:
df = pd.DataFrame(data = mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [22]:
df

    f1   f2  f3  label
0   18   43  54     69
1   99   97  59     54
2    9   97  98     51
3   90    5  91     51
4   70   18  98      7
5   68   30  60     65
6   94   61  22     68
7   80   97   8     76
8    5   19  51     86
9   26   32  61     46
10  53   97  40      9
11  16   76  89     91
12  93  100  43     98
13   9   57  68     89
14   2   89  70     64
15   2    5  97     63
16  54    2  94      1
17  89   74  51     67
18  20   20  21     25
19  10   32  71     13
20  21   65  63     40
21  18   38  89      9
22  64   23  14     26
23  43   91  41     70
24  89   98  61     25
25  30  100  30     28
26  90   79  35     32
27  76   82  40     16
28   9   52  76     51
29  69   65  11      3
30   4   74  46     93
31  98   10  94     31
32  19   53  57     96
33   5   46  69     89
34  28   69  43     69
35   3   88  43     33
36  57   75  88     57
37  67   57  77     30
38  50   19  82     62
39   8   67  59     55
40   3   31  72     53
41   8   94  36     86
42  69    8  79     72
43  37   33  86     93
44   6   10   2     64
45  90   36  54     94
46  91   22   9     35
47  57   44   2     95
48  48    4  90     42
49  35    3  19     22

In [24]:
X = df[['f1', 'f2', 'f3']]

In [25]:
X

    f1   f2  f3
0   18   43  54
1   99   97  59
2    9   97  98
3   90    5  91
4   70   18  98
5   68   30  60
6   94   61  22
7   80   97   8
8    5   19  51
9   26   32  61
10  53   97  40
11  16   76  89
12  93  100  43
13   9   57  68
14   2   89  70
15   2    5  97
16  54    2  94
17  89   74  51
18  20   20  21
19  10   32  71
20  21   65  63
21  18   38  89
22  64   23  14
23  43   91  41
24  89   98  61
25  30  100  30
26  90   79  35
27  76   82  40
28   9   52  76
29  69   65  11
30   4   74  46
31  98   10  94
32  19   53  57
33   5   46  69
34  28   69  43
35   3   88  43
36  57   75  88
37  67   57  77
38  50   19  82
39   8   67  59
40   3   31  72
41   8   94  36
42  69    8  79
43  37   33  86
44   6   10   2
45  90   36  54
46  91   22   9
47  57   44   2
48  48    4  90
49  35    3  19

In [27]:
y = df['label']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.33, random_state=42)

In [30]:
X_train

    f1  f2  f3
46  91  22   9
47  57  44   2
15   2   5  97
9   26  32  61
16  54   2  94
24  89  98  61
34  28  69  43
31  98  10  94
0   18  43  54
44   6  10   2
27  76  82  40
33   5  46  69
5   68  30  60
29  69  65  11
11  16  76  89
36  57  75  88
1   99  97  59
21  18  38  89
2    9  97  98
43  37  33  86
35   3  88  43
23  43  91  41
40   3  31  72
10  53  97  40
22  64  23  14
18  20  20  21
49  35   3  19
20  21  65  63
7   80  97   8
42  69   8  79
14   2  89  70
28   9  52  76
38  50  19  82

In [31]:
X_train.shape

(33, 3)